### ISSUE TITLE
Unify progress/rewards system

### ISSUE THREAD

**Issue by Tolmwn** [AdvancedPlugins/Jobs#36]
### Describe the bug

I found i bug at the progress file, the %required_progress% at level 2 its wronth. It's need to be 0/20 but its show 0/5. I send and screenshots for it.

### How to reproduce

![image](https://github.com/AdvancedPlugins/Jobs/assets/136921445/bb0c4245-c53e-4129-9697-d9422b63d6c7)
![image](https://github.com/AdvancedPlugins/Jobs/assets/136921445/32008b2f-66db-4cf1-9955-06a1e328adb0)

**Comment by KPGTB** [comment]
Hey! You made a small mistake during configuration. You **shouldn't** add progress into current level (currentLevel) item, because you already unlocked this level. Job menu shows required progress to unlock **next** level, so when you are on 2nd level, you need to break 20 logs to unlock 3rd level. In progress menu you see required progress to specific level, so to unlock 3rd level, you need to break 20 logs.

**Comment by Tolmwn** [comment]
1. But the progress is already in currentlevel from you. I just change the text from it.

That what i only need is to show ppl how much they need at each level to get the levelup ! I think its a bug or its from 

"# Required Progress
required-progress: "10 * %level%" "

**Comment by KPGTB** [comment]
Default configuration of progress items (in `progress.yml`):

```
lockedLevel:
  item:
    material: red_stained_glass_pane
    name: "&a%job% &fLvl. &e%level%"
    lore:
      - ''
      - '&fRewards:'
      - '  &8>>&a Global Points: &f%points%'
      - '  &8>>&a &f%rewards value%'
      - ''
      - '&fTo Unlock:'
      - '  &8>>&a &f%total_progress%/%required_progress% progress required'

unlockedLevel:
  item:
    material: green_stained_glass_pane
    name: "&a%job% &fLvl. &e%level%"
    lore:
      - ''
      - '&fRewards:'
      - '  &8>>&a Global Points: &f%points%'
      - '  &8>>&a &f%rewards value%'
      - ''
      - '&fTo Unlock:'
      - '  &8>>&a Already unlocked'

currentLevel:
  item:
    material: yellow_stained_glass_pane
    name: "&a%job% &fLvl. &e%level%"
    lore:
      - ''
      - '&fRewards:'
      - '  &8>>&a Global Points: &f%points%'
      - '  &8>>&a &f%rewards value%'
      - ''
      - '&fTo Unlock:'
      - '  &8>>&a Already unlocked'
```
