### ISSUE TITLE
Add Actions for EconomyShopGUI (free version)

### ISSUE THREAD

**Issue by Qaotix-BOSS** [AdvancedPlugins/Jobs#40]
### Describe the feature

Hi, 

Can you please add EconomyShopGUI actions? The same actions as you already did for ShopGuiPlus see below?

```
ShopGuiPlus - shopguiplus_buy

Triggered: When a player purchases an item from the shop. The progress will be the amount of items purchased

 Variables:

    root: The item that was purchased (e.g iron_sword:0)

    shop: The ID of the shop the item was purchased from (e.g foodstuffs) 

    item-id: The ID of the item in the shop (e.g 2, 6, or 8)

ShopGuiPlus - shopguiplus_buy_singular

Triggered: When a player purchases an item from the shop. The progress will always be 1

 Variables:

    root: The item that was purchased (e.g iron_sword:0)

    shop: The ID of the shop the item was purchased from (e.g foodstuffs) 

    item-id: The ID of the item in the shop (e.g 2, 6, or 8)

ShopGuiPlus - shopguiplus_spend

Triggered: When a player purchases an item from the shop. The progress will be the amount it cost the user rounded up to the nearest real number (2.4 -> 3)

 Variables:

    root: The item that was purchased (e.g iron_sword:0)

    shop: The ID of the shop the item was purchased from (e.g foodstuffs) 

    item-id: The ID of the item in the shop (e.g 2, 6, or 8)

ShopGuiPlus - shopguiplus_sell

Triggered: When a player sells an item to the shop. The progress will be the amount of items sold.

 Variables:

    root: The item that was purchased (e.g iron_sword:0)

    shop: The ID of the shop the item was purchased from (e.g foodstuffs) 

    item-id: The ID of the item in the shop (e.g 2, 6, or 8)

ShopGuiPlus - shopguiplus_sell_singular

Triggered: When a player sells an item to the shop. The progress will always be 1.

 Variables:

    root: The item that was purchased (e.g iron_sword:0)

    shop: The ID of the shop the item was purchased from (e.g foodstuffs) 

    item-id: The ID of the item in the shop (e.g 2, 6, or 8)

ShopGuiPlus - shopguiplus_profit

Triggered: When a player sells an item to the shop. The progress will be the amount it cost the user rounded up to the nearest real number (2.4 -> 3)

 Variables:

    root: The item that was purchased (e.g iron_sword:0)

    shop: The ID of the shop the item was purchased from (e.g foodstuffs) 

    item-id: The ID of the item in the shop (e.g 2, 6, or 8)
```

Thanks you! 
Greetings, Bram.
