### ISSUE TITLE
Actionbar for progressive actions

### ISSUE THREAD

**Issue by lucasdimatteo** [AdvancedPlugins/Jobs#60]
### Describe the feature

Hello,

Within our small Minecraft community, we've decided to submit this suggestion to see if it could be implemented in a future update, as we believe it would greatly enhance our experience.

Currently, we are facing two issues with progressive actions:

1. There is no intuitive way to track how much money we are earning from our actions. For example, if we are cutting down trees, we cannot easily see our level progress or the amount of money earned during that period of time (since we started the action).
2. While the "commands" function in "progress-actions" does grant the player money, it does not properly notify them of their progress.

After brainstorming, we've come up with the following idea:

In the config.yml file or within the progress-action section of example-job.yml, we suggest adding the following configuration:

```
progress-actions:
  variables:
    money: "%level% * %progress%"
  commands:
      - "eco give %player% %money%"
  # Configuration section for the actionbar.
  actionbar:
    # Message displayed by the action bar.
    message: '&a$%money% &8| &b%total_progress%&7/&b%required_progress% &8| &dLvl. %level%.'
    # How long should the actionbar wait to disappear if there is no progress in seconds.
    keep-for: 5
```

It should look something like this:
![2024-09-02_19 06 25](https://github.com/user-attachments/assets/085a2ddc-d243-42b3-88eb-149bc5de6963)

**How would this work?**
When a player joins a job and begins performing progressive actions, the actionbar will display, indicating the amount of money they are earning, their total progress, and their current job level. If no progressive action is taken for 5 seconds (keep-for), the actionbar disappears. When the player resumes the action, the money counter starts again from zero, but the actionbar will still show their current progress and level.

For example, in our community, players earn money in the Mining job by breaking stone blocks. Some users spend long periods mining stone in caves to build their houses. With this feature, they would be able to see the total money earned during that stone collection session. If they stop for 5 seconds, the money counter resets.

I hope it can be added soon. We look forward to it! Great job. Thank you

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by KPGTB** [comment]
Hey! Will be available in the next update

Syntax:
```yaml
progress-actions:
    rewards: [11, 12]
    override-message: "&7| &a+&2$%reward.11.value% &f+&0%reward.12.value% &7(&e%progress%&7/%required_progress%&7) &7[&e%job_name%&7] &7|"
```

It uses rewards from `rewards.yml` i.e.:

```yaml
"11": 
    type: money # This reward required Vault 
    name: "money reward for progress-actions"
    variables:
        value: "(%level% * %progress% * 0.1) * (1 + (%booster% / 100))"
    value: "%value%"

"12":
    type: item
    name: "item reward for progress-actions"
    variables:
        value: "(%level% * %progress% * 2) * (1 + (%booster% / 100))"
    items:
        "1":
            material: coal:0
            amount: "%value%"
```
