### ISSUE TITLE
[ADVANCEDJOBS] seems %value% placeholder doesn't work correctly.

### ISSUE THREAD

**Issue by loyfael** [AdvancedPlugins/Jobs#73]
### Describe the bug

Hello !
Rewards by money doesn't work at all. I keep getting an error from my economy plugin (XConomy) and it doesn't seem to want the value returned by the placeholder value. I've even tried in-game with the command `eco give Paaz_ 1` it works correctly.

Note that I also tested with Vault with the example given, but nothing worked.

### How to reproduce
```
'myst':
  type: command
  name: '§d%value% Mysts'
  variables:
    value: “1000 * %level%”
  commands:
    - eco give %player name% %value%'
```

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/8af75beb-709e-4bfc-b528-ba59925db3fa)
