### ISSUE TITLE
Player not receiving money

### ISSUE THREAD

**Issue by EndersWolf3072** [AdvancedPlugins/Jobs#76]
### Describe the bug

One of the players stopped receiving money on their hunter job. They haven't reached a max limit. Last known they were on level 19. I had them switch to another job and still wasn't making any money. I tried a job myself and wasn't making any money either. I haven't changed anything as of late that would cause this that I remember. I don't have any other plugins that would effect players receiving money. It was working then just recently it stopped. I'm using v 1.5.18 for 1.21.3

### How to reproduce

Select job... say... Lumberjack for example. I used diamond axe on a 2x2 spruce tree.

**Comment by EndersWolf3072** [comment]
https://github.com/user-attachments/assets/6bba5c8c-4284-4cae-8013-f3230759eed1

**Comment by KPGTB** [comment]
Hey! Firstly, please update the plugin to the latest version (1.6.13) and let me know if that problem has been already fixed or not

**Comment by EndersWolf3072** [comment]
Ok will do. I’ll let you know, I’ll update it when I can get to my computer tonight

**Comment by EndersWolf3072** [comment]
I got it updated. I tried that lumberjack job to test and no luck. But then I switched to farming and no luck there either.

**Comment by EndersWolf3072** [comment]
Just checked the config and looks like nothing changed that would cause it to not give players money.

**Comment by KPGTB** [comment]
Can you send me lumberjack job and rewards configuration?

**Comment by KPGTB** [comment]
Btw that video doesn't show anything. Please show progress after cutting that tree. Also by default, player receive money after levelling up.

**Comment by EndersWolf3072** [comment]
```
actions-version: 2

type: block-break

variable:
  root:
    - ___LOG # All materials which contains _LOG
    - crimson_stem

name: 'Lumberjack'

# Required Progress
required-progress: "5 * (%level% ^ 2)"

# Points given after task is completed
points-rewarded: "1 * %level%"

# Required points to access this job
required-points: 0

# Is this a premium job?
premium: false

# rewards are taken from rewards.yml file
default-rewards: [ 1 ]

# when level-rewards contains level, give default & level rewards or only level-rewards
both-rewards: false

# levels info
level-rewards:

notify-at-percentages: [ 10, 25, 50, 75, 100 ]

whitelisted-worlds: []
blacklisted-worlds: []
blacklisted-regions: []
whitelisted-regions: []

item:
  material: oak_log
  name: '&2✦ &a&lLumberjack&a Job &7[Lvl. %level%] '
  lore:
    - '&7 To level up in this job, you must'
    - '&7 break any &a%required_progress% &7wood logs.'
    - ''
    - '&2• &f&lCurrent Level &8» &7Lvl. %level% '
    - '&2• &f&lActive &8» %active%'
    - ''
    - '&a&lJob Progress'
    - '&2• &a%progress_bar% &7(&f%total_progress%&7/&f%required_progress%&7)'
    - '&2• &a%rewards%&f Reward'
    - ''
    - '&2• %action%'
  ```

**Comment by EndersWolf3072** [comment]
```
'1': # The id of the reward
  type: command
  name: '$%value%'
  variables:
    value: "(0.1 * (2 * (%level% ^ 2))) * (1 + (%booster% / 100))"
  commands:
    - 'eco give %player% %value%'

'2': # The id of the reward
  type: command
  name: '$%value%'
  variables:
    value: "(0.1 * (2 * (%level% ^ 2))) * (1 + (%booster% / 100))"
  commands:
    - 'eco give %player% %value%'

# Example Reward
'100':
  type: item
  name: '&eWOAH! Something cool'
  variables:
    diamonds: "(%level%) * (1 + (%booster% / 100))"
    coals: "(%level% * 3) * (1 + (%booster% / 100))"
  items:
    '1': # The first item reward (required)
      material: diamond_block:0
      amount: "%diamonds%"
      name: '' # If left null, the item will have the default Minecraft name.
      lore: [] # If left null, the item will have no lore.
      glow: true # Whether the item will have an enchantment 'glow'.
    '2': # The second item reward (not required) -> You can have more than two.
      material: coal_block:0
      amount: "%coals%"
      name: ''
      lore:
        - '&7An &bawesome &7lore, for an &eawesome &7coal block'

```
