### ISSUE TITLE
Error in console when using decimal numbers in the pitch of sounds.

### ISSUE THREAD

**Issue by whoisalee** [AdvancedPlugins/Jobs#83]
### Describe the bug

After following the correct format for using sounds in menu actions, I tried using a decimal number in the pitch to achieve an effect with the sound. As a result, it plays, but it triggers an error in the console, stating that an incorrect format is being used every time this object is activated.

### How to reproduce

1. In the actions of any object in a menu, the following must be placed:

```yml
      - '[sound] {ENTITY_CHICKEN_EGG:1:0.9}'
```

2. Go to the menu where you placed the object with the corresponding action and interact with it. When you do this, the sound will play correctly; however, the error will appear in the console.

### Screenshots / Videos

https://imgur.com/a/tfe0qpt

### Server Log

It's not necessary, everything else works fine.

**Comment by KPGTB** [comment]
Hey! Will be fixed in one of the next updates

**Comment by whoisalee** [comment]
Hi, I saw you marked this post as completed a while ago, but it still hasn't been resolved.

I'm using AdvancedJobs version 1.8.12.

**Comment by KPGTB** [comment]
Hey! Are you sure that this is the same error? I've copied your code and everything works fine for me

**Comment by whoisalee** [comment]
Yes, my Minecraft server runs on version 1.21.4 with the latest version of AdvancedJobs. The error persists, as I reported.

**Comment by KPGTB** [comment]
As I said, everything works fine on my local server. Can you send me yours menu configuration?

**Comment by whoisalee** [comment]
The problem comes from the item that is in position 39, when it has a value less than 1 in the pitch, it will use 0.5 and will say that error that I shared before

```yml
menu-title: '&8Menu title'
menu-rows: 5

jobs-slots:
  slots: '11...15, 20...24'

menu:
  '39':
    item:
      material: STONE
      name: '{#FFDD54}Item name'
      lore:
        - ''
        - '&fItem description'
        - ''
    actions:
      - '[menu] {leaderboard}'
      - '[sound] {ENTITY_CHICKEN_EGG:1:0.9"}'

  '40':
    item:
      material: STONE
      name: '{#FFDD54}Item name'
      lore:
        - ''
        - '&fItem description'
        - ''
    actions: 
      - '[menu] {close}'
      - '[sound] {ENTITY_CHICKEN_EGG:1:1}'

  MF:
    slots: fill 
    item:
      material: black_stained_glass_pane
      name: '&r '
```
