### ISSUE TITLE
The content of a title is interrupted if a hexadecimal color is placed inside it.

### ISSUE THREAD

**Issue by whoisalee** [AdvancedPlugins/Jobs#84]
### Describe the bug

The title displayed when leveling up gets interrupted if there is a hexadecimal color code within its content, extending up to the first '}', causing the rest of the message to be excluded.

### How to reproduce

1. To perform actions upon leveling up, you must specify any titles or subtitles that contain hexadecimal colors (the default format was followed).

```yml
notification-method: action bar # How notifications will be sent to players. Options: action bar, chat, action bar & chat or none.
level-up-actions:
- '[title]{&#FF92F9TITLE CONTENT}'
- '[subtitle]{&fContent of my {#DE99DA}  subtitle {#DE99DA}message}'
```

2. You will need to level up any job to trigger this event, which will display the corrupted format.

### Screenshots / Videos

https://imgur.com/a/6Odf2bx

### Server Log

It's not necessary, everything else works fine.
